import * as Yup from "yup";

export const validationSchema = Yup.object().shape({
  staff: Yup.object().shape({
    checkbox: Yup.boolean(),
    staffName: Yup.string(),
  }),
  admission: Yup.object().shape({
    applicationNo: Yup.string().required("required"),
    admissionNo: Yup.string().required(" required"),
    emisNo: Yup.string().required("required"),
    applicationReceivedBy: Yup.string().required("required"),
    DateOfAdmission: Yup.string().required("required"),
    AdmissionRequiredFor: Yup.string().required("required"),
    academicYear: Yup.string().required("required"),
    grade: Yup.string().required("required"),
  }),
  student: Yup.object().shape({
    nameInEnglish: Yup.string().required("Required"),
    nameInTamil: Yup.string().required("Required"),
    gender: Yup.string().required("Required"),
    dateOfBirth: Yup.string().required("Required"),
    dataOfBirthInWords: Yup.string().required("Required"),
    aadharCardNo: Yup.string().required("Required"),
    motherTongue: Yup.string().required("Required"),
    nationality: Yup.string().required("Required"),
    caste: Yup.string().required("Required"),
    bloodGroup: Yup.string().required("Required"),
    religion: Yup.string().required("Required"),
    community: Yup.string().required("Required"),
  }),
  parent: Yup.object().shape({
    fatherDetails: Yup.object().shape({
      name: Yup.string(),
      dateOfBirth: Yup.string(),
      mobileNo: Yup.string(),
      emailAddress: Yup.string(),
      aadarNo: Yup.string(),
      educationQalification: Yup.string(),
      occupation: Yup.string(),
      annualIncome: Yup.string(),
    }),
    motherDetails: Yup.object().shape({
      name: Yup.string(),
      dateOfBirth: Yup.string(),
      mobileNo: Yup.string(),
      emailAddress: Yup.string(),
      aadarNo: Yup.string(),
      educationQalification: Yup.string(),
      occupation: Yup.string(),
      annualIncome: Yup.string(),
    }),
  }),
  siblings: Yup.array().of(
    Yup.object().shape({
      sibling: Yup.string(),
      name: Yup.string(),
      class: Yup.string(),
      dateOfBirth: Yup.string(),
      instituteName: Yup.string(),
      academicYear: Yup.string(),
    })
  ),
  previousStudy: Yup.object().shape({
    instituteName: Yup.string().required("Required"),
    academicYear: Yup.string().required("Required"),
    class: Yup.string().required("Required"),
    medium: Yup.string().required("Required"),
    matric: Yup.string().required("Required"),
    marks: Yup.string(),
  }),
  upload: Yup.object().shape({
    transferCertificate: Yup.string().required("Required"),
    studentPhoto: Yup.string().required("Required"),
    birthCertificate: Yup.string(),
    tenthMarksheet: Yup.string(),
  }),
});

export const initialState = {
  staff: {
    checkbox: false,
    staffName: "",
  },
  admission: {
    applicationNo: "",
    admissionNo: "",
    emisNo: "",
    applicationReceivedBy: "",
    DateOfAdmission: "",
    AdmissionRequiredFor: "",
    academicYear: "",
    grade: "",
  },
  student: {
    nameInEnglish: "",
    nameInTamil: "",
    gender: "",
    dateOfBirth: "",
    dataOfBirthInWords: "",
    aadharCardNo: "",
    motherTongue: "",
    nationality: "",
    caste: "",
    bloodGroup: "",
    religion: "",
    community: "",
  },
  parent: {
    fatherDetails: {
      name: "",
      dateOfBirth: "",
      mobileNo: "",
      emailAddress: "",
      aadarNo: "",
      educationQalification: "",
      occupation: "",
      annualIncome: "",
    },
    motherDetails: {
      name: "",
      dateOfBirth: "",
      mobileNo: "",
      emailAddress: "",
      aadarNo: "",
      educationQalification: "",
      occupation: "",
      annualIncome: "",
    },
  },
  siblings: [
    {
      sibling: "",
      name: "",
      class: "",
      dateOfBirth: "",
      instituteName: "",
      academicYear: "",
    },
  ],
  previousStudy: {
    instituteName: "",
    academicYear: "",
    class: "",
    medium: "",
    matric: "",
    marks: "",
  },
  upload: {
    transferCertificate: "",
    studentPhoto: "",
    birthCertificate: "",
    tenthMarksheet: "",
  },
};
